{
 "title": "Dashboard Informações Basicas Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "MySql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ultimas Vendas",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "sweetcontrol_db",
     "rawSql": "SELECT \r\n  produto, \r\n  categoria, \r\n  valor, \r\n  DATE_FORMAT(data_venda, '%d/%m/%Y') AS \"data\"\r\nFROM vendas\r\nORDER BY data_venda DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Indicadores-Chave",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sweetcontrol_db",
     "rawSql": "SELECT SUM(valor) as 'Total de Vendas (hoje)'\r\nFROM vendas \r\nWHERE DATE(data_venda) = CURDATE();"
    },
    {
     "dataset": "sweetcontrol_db",
     "rawSql": "SELECT AVG(valor) as 'Ticket Médio Geral'\r\nFROM vendas;"
    },
    {
     "dataset": "sweetcontrol_db",
     "rawSql": "SELECT SUM(valor) as 'Total de Vendas (Geral)'\r\nFROM vendas;"
    },
    {
     "dataset": "sweetcontrol_db",
     "rawSql": "SELECT COUNT(id) as 'Total de Pedidos Registraados'\r\nFROM vendas;"
    }
   ]
  },
  {
   "title": "Vendas por Categoria",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sweetcontrol_db",
     "rawSql": "SELECT categoria, SUM(valor) AS total_vendas\r\nFROM vendas\r\nGROUP BY categoria\r\nORDER BY total_vendas DESC;"
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Taxa de Requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "RPS Total"
    }
   ]
  },
  {
   "title": "Latência p95",
   "type": "timeseries",
   "description": "Mostra o tempo em segundos que 95 das requisições levaram para completar",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Latência p95"
    }
   ]
  },
  {
   "title": "Taxa de Erros (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{code=~\"4.*|5.*\"}[1m]))\r\n/\r\nsum(rate(http_requests_total[1m]))",
     "legendFormat": "Taxa de Erros"
    }
   ]
  },
  {
   "title": "Vendas por Minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(sweetcontrol_vendas_total[1m])) by (categoria)",
     "legendFormat": "{{categoria}}"
    }
   ]
  }
 ]
}